# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tvshow_pb2 as tvshow__pb2


class TvshowRPCStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getGoodTvShows = channel.unary_stream(
        '/tvshows.TvshowRPC/getGoodTvShows',
        request_serializer=tvshow__pb2.ShowRequest.SerializeToString,
        response_deserializer=tvshow__pb2.ShowResponse.FromString,
        )


class TvshowRPCServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getGoodTvShows(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TvshowRPCServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getGoodTvShows': grpc.unary_stream_rpc_method_handler(
          servicer.getGoodTvShows,
          request_deserializer=tvshow__pb2.ShowRequest.FromString,
          response_serializer=tvshow__pb2.ShowResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tvshows.TvshowRPC', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
