# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tvshow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tvshow.proto',
  package='tvshows',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctvshow.proto\x12\x07tvshows\"!\n\x0bShowRequest\x12\x12\n\nmin_rating\x18\x01 \x01(\t\",\n\x0cShowResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06rating\x18\x02 \x01(\t2N\n\tTvshowRPC\x12\x41\n\x0egetGoodTvShows\x12\x14.tvshows.ShowRequest\x1a\x15.tvshows.ShowResponse\"\x00\x30\x01\x62\x06proto3')
)




_SHOWREQUEST = _descriptor.Descriptor(
  name='ShowRequest',
  full_name='tvshows.ShowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_rating', full_name='tvshows.ShowRequest.min_rating', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=58,
)


_SHOWRESPONSE = _descriptor.Descriptor(
  name='ShowResponse',
  full_name='tvshows.ShowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tvshows.ShowResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='tvshows.ShowResponse.rating', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ShowRequest'] = _SHOWREQUEST
DESCRIPTOR.message_types_by_name['ShowResponse'] = _SHOWRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShowRequest = _reflection.GeneratedProtocolMessageType('ShowRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHOWREQUEST,
  '__module__' : 'tvshow_pb2'
  # @@protoc_insertion_point(class_scope:tvshows.ShowRequest)
  })
_sym_db.RegisterMessage(ShowRequest)

ShowResponse = _reflection.GeneratedProtocolMessageType('ShowResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHOWRESPONSE,
  '__module__' : 'tvshow_pb2'
  # @@protoc_insertion_point(class_scope:tvshows.ShowResponse)
  })
_sym_db.RegisterMessage(ShowResponse)



_TVSHOWRPC = _descriptor.ServiceDescriptor(
  name='TvshowRPC',
  full_name='tvshows.TvshowRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=184,
  methods=[
  _descriptor.MethodDescriptor(
    name='getGoodTvShows',
    full_name='tvshows.TvshowRPC.getGoodTvShows',
    index=0,
    containing_service=None,
    input_type=_SHOWREQUEST,
    output_type=_SHOWRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TVSHOWRPC)

DESCRIPTOR.services_by_name['TvshowRPC'] = _TVSHOWRPC

# @@protoc_insertion_point(module_scope)
